[package]
name = "naviscope"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.6"
tree-sitter = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
walkdir = "2"
log = "0.4"

[build-dependencies]
cc = "1.0"
