[package]
name = "naviscope-ingest"
version = "0.5.5"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
naviscope-api = { workspace = true }
async-trait = { workspace = true }
