[package]
name = "naviscope-api"
version = "0.5.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
lasso = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
