[package]
name = "naviscope-core"
version = "0.2.1"
edition = "2024"

[dependencies]
petgraph = { version = "0.8", features = ["serde-1"] }
tree-sitter = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
walkdir = "2.5"
log = "0.4"
ignore = "0.4.25"
rayon = "1.11.0"
notify = "8.2.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
regex = "1.11.1"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "sync", "time", "fs"] }
schemars = "1.2.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-appender = "0.2.4"
rmp-serde = "1.3.1"
once_cell = "1.20"
tower-lsp = "0.20"

[build-dependencies]
cc = "1.2"
